#!/bin/bash

# Inspired by https://darrenjw2.wordpress.com/2012/11/28/getting-a-headless-raspberry-pi-to-speak-its/
#apt-get install espeak


sudo apt-get update
# to get dig
sudo apt-get -y install dnsutils
# to get curl
sudo apt-get -y install curl

cd /etc/init.d
sudo chmod a+x speakMyIPs
sudo update-rc.d -f speakMyIPs defaults
