#! /bin/sh

dig=/usr/bin/dig
python=/usr/bin/python3
hostname=/bin/hostname

#########################################################
# For cleanup, see https://gist.github.com/naholyr/4275302#file-service-sh
###########
me=`basename "$0"`
publicString=""
privateString=""
# Use "dig" to figure out our external/WAN/public address
[ -f "$dig" ] && myWANip=`$dig +time=5 +short myip.opendns.com @resolver1.opendns.com`

case "$1" in
    start)
	echo "Starting script $me"

	# Determine our Public Address
	echo " -- determining our Public Address"
	# There are a variety of reasons this might not work:
	#  - dig might not be installed
	#  - we might not have a WAN IP address
	#  - OpenDNS' DNS server(s) might be blocked (or down)
	[ "$myWANip" ] && publicString="public IP: $myWANip &"

	# Determine our Private Address(es)
	echo " -- determining our Private Address(es)"
	private=`$hostname -I`
	privateString="private IP(s): $private"

	# Template construction
	string=$publicString" "$privateString
	echo $string # to stdout

	# if python installed, then try to talk to the SenseHat
	if [ -f $python ]
	then
	    $python <<EOF
from sense_hat import SenseHat
sense = SenseHat()
sense.show_message("$string")
sense.show_message("$string")
EOF
	fi
    
	# echo $string | espeak -s 120 -v en-uk
	echo 0
	;;  

    stop)    
	echo "Stopping script $me"
	echo 0
	;;  

    *)
	echo "Usage: /etc/init.d/$me {start|stop}"
	exit 1
	;;
esac
